services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./ha-config:/config
      - ./custom_components/ecosense_radon:/config/custom_components/ecosense_radon
    ports:
      - "8123:8123"
    restart: unless-stopped
    privileged: true
